### ISSUE TITLE
DaheeKim

### ISSUE THREAD

**Issue by dahee-diana96** [seungjaepack/Toy_Project_EDA#4]
데이터 처리 (변수 생성, 지정, 데이터 프레임 생성)

- [x] 변수 생성
- [x] 변수 지정
- [x] 데이터 프레임 생성

[현재상태]
- 적용할 데이터 분석 기법 확인을 위해 데이터를 살펴보는 중
    - 상품군별 온라인 거래액 데이터만으론 마땅한 통계적 방법을 적용해보기엔 어려운 상태
    - 아직까지 주어진 데이터셋만으로 상관관계같은 분석을 적용하기엔 또다른 feature들이 부족한 듯

[제안]
    - 월별 시간을 기준으로 두고 있으니, 또다른 '월별'데이터를 더 찾아서 결합해보는 방법

**Comment by dahee-diana96** [comment]
통계적 방법을 적용해보기 위해선 더 많은 feature들이 필요할 것 같고, 그 후에 결합된 데이터를 이용하여 normalize(표준화?)를 한 이후에 통계 방법을 적용해볼 수 있을 것 같습니다.

**Comment by dahee-diana96** [comment]
210929
To-Do

데이터 시각화
- [x] 온라인/모바일 합계 바 그래프
- [x] 산업군별 증감액/증감률 바 그래프 (3월 기준)

**Comment by seungjaepack** [comment]
Step1  코로나 팬더믹 (2020.03 신천지 확진자 급증)과 전년 동월(2019.03) 대비 카테고리별 소비 증감액 / 증감율 시각화 확인 완료
- 화장품과 여행 및 교통 피처가 감소한 게 확연히 보임
- 음식 카테고리 (배달 포함) 거래액이 많이 증가한 것 확인
-  증감율의 경우 증감액에 비해 scale 적으로 카테고리별 차이가 눈에 띔

**Comment by seungjaepack** [comment]
Step2. 코로나 팬더믹 이후 (2020.03~2021.07) 과 팬더믹 이전(2017.01 ~ 2020.02) 카테고리별 소비 증감액/증감율  시각화 확인 작업 : 20210930 예정

**Comment by seungjaepack** [comment]
- 20210929 코드 리뷰
1. 2019년 3월 항목의 row 추출
mobile_march_2019 = mobile_df_01[mobile_df_01.index=='2019. 03']
2. 2020년 3월 항목의 row 추출
mobile_march_2020 = mobile_df_01[mobile_df_01.index=='2020. 03']
3.  증감액 구하기 (2020, 2019년 3월)
mobile_march_subtract = np.subtract(mobile_march_2020, mobile_march_2019)
4. 증감률 구하기
mobile_march_rate = np.divide(mobile_march_subtract, mobile_march_2019) * 100

**Comment by dahee-diana96** [comment]
210930

To-Do

- [x] 코드 정리

태양님이랑 변수 영문화 작업 완료했습니다.

태양님과 의논 후 작업할 내용
- [x] 쇼핑거래액 데이터와 코로나 데이터 merge (모바일쇼핑 거래액 데이터 & 코로나 데이터)
- [x] 상품군들과 코로나 데이터의 heatmap 생성
    - 확진자 수 (국내 + 해외유입) 기준

**Comment by dahee-diana96** [comment]
- [x] 상품군들과 코로나 데이터의 확진자 수 기준 heatmap을 correlation 값들이 큰 순서대로 다시 정렬
- [x] 연령대 데이터 X 상품군별 데이터 heatmap 생성
- [x] pairplot 생성

**Comment by seungjaepack** [comment]
- 미팅 시 말씀 드렸던 작업 시 참고할 내용 남겨 드려요 ^^
1.연령대 데이터 X 상품군별 데이터 heatmap 생성 -> 상관계수로 정렬하여 heatmap  시각화 ->  양/음의 관계 피처 10개 추출
2. pairplot 생성 ->  세부적으로 확인할 피처 추출하기

**Comment by dahee-diana96** [comment]
어제(210929)에 빼먹은 내용:
- 월별 '합계' 거래금액에 대한 인터넷과 모바일 간의 거래액 비교 그래프를 확인
    - 모바일 거래액의 증가세가 월등히 큼

오늘(210930) 작업하고 확인한 내용:
- 태양님과 변수명 영문화 작업 완료
- 모바일 쇼핑거래액 데이터와 코로나 월별 확진자 데이터 merge  작업 완료
- 총 확진자 수 (국내 + 해외유입) 기준으로 상품군들의 pearson's correlation heatmap 생성하여 완료   
    - 상위 5개: food_service, electronic, pets, kids, groceries
    - 하위 5개: etc(negative value), travel(negative value), culture_ls, shoes, clothes
        - 하위 항목들은 correlation 값이 0에 가까우므로 중요도가 높아보이진 않음
- 확진자 수를 기준으로 상위 5개 산업군(food_service, electronic, pets, kids, groceries)들 각각의 scatterplot들을 pairplot으로 생성완료
    - 가장 강한 상관관계: food_service, 가장 약한 상관관계: etc
- 모바일 쇼핑거래액 데이터와 코로나 월별 확진자 데이터와 코로나 연령별 확진자 데이터 merge 완료
- 연령대별 산업군과의 correlation heatmap 생성완료
    - 엑셀로 연령대별 top10 산업군들과 negative 산업군들 정리 완료

**Comment by dahee-diana96** [comment]
내일(211001)에 개인적으로 시급한 작업:
1. .... 코드 정리... 매우 시급... 매우 중구난방인 상태....
2. 시각화 자료들 보강

**Comment by seungjaepack** [comment]
내일 오전에 지금까지 시각화한것과 오늘 저녁에 미팅한 커맨트 내용 함께 정리해보아요~!

**Comment by dahee-diana96** [comment]
앗 일단 저 혼자 정리부터 필요할 것 같아서요! 정말 승재님도 혼란스러우실 정도로 노답의 상태입니다 ㅎㅎ... 저부터 얼추 정리된 이후에 같이 봐주시면 좋을 듯 합니다!

**Comment by seungjaepack** [comment]
넵~ 이슈에다가 정리된 내용 요약해서 남겨주시면 커맨트 달게요~ ^^

**Comment by dahee-diana96** [comment]
211001
To-do
- [x] 코드 정리
- [x] 인터넷쇼핑에 대한 시각화 자료 만들기


오늘 하루 정리:
- 코드 정리 완료
    - SSAC_Toy_Project_5조 > CODE > Part Code 폴더 내에 '코드_그래프_정리_20211001' 구글닥 생성완료
- 코드 자료 섹션 분리 (위에 가설 정리 내용 복사 붙여서 각 항목에 그래프 배치하기) 중 가설 1에 관련한 시각화 자료 배치 완료
    - SSAC_Toy_Project_5조 > Modeling 폴더 내에 '코드_그래프_정리_20211001' 구글닥 생성완료
- 태양님이 전달해주신 데이터(카테고리 연령대별 조회수)와 코로나 연령대별 확진자 데이터를 통해 연령대별과 카테고리 연령대별 조회수간의 상관관계 파악 --> grocery와 culture만 파악 완료
    - 음의 관계가 가장 강한 카테고리인 culture에서 상관관계가 양수로 나타남 --> 사람들이 조회는 하지만 구매로 이어지지 않았다는 것을 알 수 있음

내일 마저 할 작업:
- 코드만 따로 정리하는 파일 작업
- 코드 자료 섹션 분리 마저 완료하기
- grocery와 culture 카테고리 이외에 나머지 카테고리도 파악하기

**Comment by dahee-diana96** [comment]
20211001

To-Do
- [x] 가설에 따른 시각화 자료 배치
- [x] 대가설2에 대한 시각화 작업
- [x] 대가설4에 따른 시각화 작업

현재 상태:
- 가설에 따른 시각화 자료 배치 중
- 대가설4에 따른 시각화 작업 중 (인터넷: 카테고리 6개 중 3개 완료, 모바일: 모바일 데이터 아직 받지 못함)

**Comment by dahee-diana96** [comment]
20211003
- 대가설4에 따른 시각화 작업 완료 (인터넷쇼핑은 완료. 모바일 데이터를 아직 받지 못함)
- 토요일(20211002)에 작업했던 잔차와 normalization 관련 코드와 그래프들 업로드 완료 (at '코드_그래프_정리_20211003' google doc) --> 보라색 코드에 해당함. 그리고 해당 그래프들을 subplot으로 나타냄
- mobile_df와 internet_df의 boxplot들, mobile_df에서 유일하게 outlier가 있었던 'etc_service'에 대한 분석 내용들을 업로드 완료 (at '코드_그래프_정리_20211003' google doc)

가설에 따른 시각화자료 배치 검토 필요

**Comment by dahee-diana96** [comment]
20211004 

- 그동안 작성해 온 코드와 시각자료들은 '코드_그래프_정리' 구글닥에 업로드 완료
- 빠진 내용이 있는지 검토 필요
- 가설에 따른 시각화자료 배치 검토 필요

To-Do
Part 1.
- [ ] 대가설4에 따른 모바일쇼핑 시각화 자료 만들기
- [x] 노션에 대가설 1에 해당하는 내용 정리 (at 'Codebase' --> 'Modeling')

Part 2.
- [x]  노션에 대가설 2에 해당하는 내용 정리 (at 'Codebase' --> 'Modeling')

Part 3.
- [ ]  노션에 대가설 3에 해당하는 내용 정리 (at 'Codebase' --> 'Modeling')

Part 4.
- [ ]  노션에 대가설 4에 해당하는 내용 정리 (at 'Codebase' --> 'Modeling')

**Comment by seungjaepack** [comment]
- 추가 내용 : 
1. 파트별 정리하다가 인기 검색어를 통해 인사이트가 필요한 부분 확인하기
2. Part 1~ Part 4는 도출된 인사이트를 고려한 스토리라인을 가지고 정리하기
