### ISSUE TITLE
Taeyangsim_Part

### ISSUE THREAD

**Issue by taeyang1224** [seungjaepack/Toy_Project_EDA#5]
- 데이터 수집 및 처리 (데이터 전처리, 코드관리)
- [x]  수집된 데이터를 기반으로 데이터 분석하기 위한 최종적 데이터 구조화
- [x]  코로나 관련 데이터 수집

- 인사이트 도출 (경영학적 접근)
- [x]  정리된 데이터를 기반으로 새로운 인사이트 도출
- [x] SWOT분석을 통해 데이터 분석이 가능한지 찾아보기

- 문서정리
- 일별 회의 내용 및 Issue를 doc 파일로 정리 후 push는 어떤지 제안

- 추가적인 사항은 Comment로 생성

**Comment by taeyang1224** [comment]
210929 - Issue
- 현재 참고하는 사이트의 데이터양이 생각보다 많지 않음
- 월별로 끊어서 온라인쇼핑별, 모바일쇼핑별, 총계 를 끊어서 concat해봤지만 불필요한 데이터들의 중복이라고 생각
- 각 데이터의 shape은 (49, 26)인 상태 
- 데이터의 수집이 더 필요하다고 생각
- 코로나 데이터는 공공데이터포털 등 데이터공유 사이트에 많이 있는것으로 확인

**Comment by taeyang1224** [comment]
210929 - To do
- [x] 코로나 데이터 월별 확진자 수 변화 & 일별 확진자 수 변화
- [x] 쇼핑거래 데이터 컬럼 영문화
- [x] 코로나 데이터와 쇼핑거래 데이터 변수명 정리

**Comment by seungjaepack** [comment]
- 코로나 환자수 데이터 테이블 수치 1차 리뷰
1. 2020.1월 부터 2월 중/후반까지 컬럼 열에 비어있는 값들이 존재함 : 결측값에 대한 해석 -> 초반에 코로나 집계에 대한 시스템이 안정화되지 않았으면 초반에는 환자수, 검사자수와 같이 주항목에 대한 기록이 이루어 졌고 확산세가 커지는 2월 후반에서 3월에는 누적 집계 열을 삽입하여 데이터화 했을 것을 추정함, 해당 값은 누적값이기 때문에 3월 기점으로 거슬러 올라가 데이터를 삽입하여 데이터 처리 예정

2. 소비 data set index (월) 단위로 변경 : 코로나 환자수는 일단위로 원단위로 변경하여 데이터 프레임 재구성

3. 데이터 전처리 이후 작업 
    1) 일별에 따른 환자수 : bar plot
    2) 월별에 따른 환자수 : bar plot
    3) 2번 항목과 소비 총액(코로나 이후 2020.03 ~ 2021.07)에 상관 관계 분석
    3) 코로나 컬럼 피처들과 소비 총액과 상관 관계 분석
    4) 양의 상관관계를 가지는 상품 카테고리 확인
    5) 양의 상관관계에 상품에 대한 데이터 수집 또는 데이터 가공 후 모델링

**Comment by seungjaepack** [comment]
- 코로나 데이터 전처리 리뷰 
1. data set 출처에서 월별 필터링 가능한지 한번 더 확인 후 다음 2~3 안을 진행하여 데이터 전처리 해 볼 것
2. 인덱스 날짜 형식을 년-월-일을 년-월로 변경 후 월별 데이터 취합 해 볼 것
3. 인덱스 날짜를 년-월로 string으로 접근하여 추출 해 볼 것

**Comment by taeyang1224** [comment]
1. 기존 코로나 데이터 보다 새로운 코로나 데이터가 괜찮다고 생각하여 코로나 data set을 변경
2. 데이터 확인 해보니, 비어있는 값 " - " 으로 표기되어있음 -> " - " 표기는 0이라는것을 파악. " - " 값을 0으로 수정
3. 소비 data set 컬럼을 영문으로 변경 및 코로나 data set 컬럼 영문으로 변경 후 항목 설명 정리
4. 코로나 data 일자별 확진자 수를 시각화 -> 많은 양의 data를 가지고 있어 확진자 증가량 파악은 가능하나 보기힘든 그래프로 보여짐
5. 코로나 data set index를 월별로 수정할 예정

**Comment by taeyang1224** [comment]
210930 - To do

- [x] 코로나 data set 월별 data set으로 변경
- [x] 코로나 data 시각화
- [x] 변수 항목 변경 후 리스트 공유
- [x] 코비드 월별 데이터와 카테고리별 거래액 데이터의 feature 간 상관관계 확인

점심시간 이후에 다희님과 같이 작업할 수 있을거같습니다.

**Comment by taeyang1224** [comment]
Covid data 시각화 

1. Covid data를 월별 확진자 수 시각화
- data를 시각화하여 보니 covid가 발생하고 방역준수를 강하게 시행하였던 20년의 경우 확진자의 수가 10000명을 넘지 않으나, covid가 생활화되고 익숙해진 21년의 경우 확진자 수가 급격하게 상승한것이 파악
- 또한, 명절이나 크리스마스같은 월이 있는 경우에 접촉이 많다보니 확진자 수가 증가하는것이 보여짐
- 21년 6월의 확진자와 7월의 확진자의 수가 2만 5천명 가량의 차이가 발생하면서 7월부터 급격하게 확진자의 수가 증가하는것이 파악
- 현재 9월 5만 5천명 이상의 확진자 수가 나타나며, 많은 나라에서 위드 코로나를 언급하면서 시간이 지남에 따라 유지되거나 증가할것이라고 예측이 됨


다희님과 같이 분석을 통한 결과

1. 코로나 팬더믹 (2020.03)과 전년 동월(2019.03) 대비 카테고리별 소비 증감액/증감율 모바일쇼핑과 온라인쇼핑 시각화 비교
- 모바일쇼핑과 온라인쇼핑의 증감액/증감율을 비교해보니 확연한 차이가 발생하는것이 보임

- 증감액 시각화 경우, 모바일쇼핑은 합계의 부분이 강하게 나타나는것을 확인할수 있고, 모바일쇼핑과 온라인쇼핑 둘 다 여행 카테고리는 하락한것이 보임 -> 팬더믹 상황으로 여행을 하지못하는 부분으로 여행카테고리 또한, 감소한다는것이 파악 가능

또한, 모바일쇼핑의 경우 음식서비스의 증가가 높지만 온라인쇼핑의 경우 음식서비스의 증가가 낮은걸로 보아, 서비스 카테고리는 모바일을 많이 사용하는것이 파악 가능

- 증감율 시각화 경우,  모바일쇼핑의 경우에는 전반적인 카테고리의 증감율이 상승했다는것이 파악
모바일쇼핑과 온라인쇼핑 모두 여행 카테고리와 문화 카테고리는 하락한다는것이 파악
하지만, 모바일 쇼핑의 경우 음식료품, 음식 서비스 등 집에서 생활하는 부분에 영향을 미치는 카테고리가 상승했지만, 온라인쇼핑의 경우 자동차 및 자동차용품 카테고리가 두드러지게 증가했다는것이 보임 -> 여행을 가지 못하는 사람들이 차박을 하는 현재 트렌드와 영향이 미친다고 생각 -> 트렌드 부분과 병합하면 좋은 결과물이 보일 수 있다고 생각

2. 코로나 확진자 수와 쇼핑 거래액에 대한 상관관계를 찾아보려 pairplot을 이용하여 총거래액,  확진자수, 사망자 수,  코로나시각화를 해봤지만 상관관계를 찾기는 어렵다는 점이 나타남

**Comment by taeyang1224** [comment]
1. 코로나_월별, 코로나_나이, 거래액, data set 표준화 및 구조화 완료
2. 변수 항목 변경 후 공유 완료
3. 코로나 월별 데이터와 카테고리별 거래액 데이터의 feature 간 상관관계 확인
4. 모바일 data와 온라인 data의 거래액 비교 확인

**Comment by taeyang1224** [comment]
오늘 할 일
- click_data 정리 후 전처리 방법 생각
- shopping data와 네이버 카테고리와 비교하여 테이블 생성

내일 할 일
- click_data 전처리 완료 
- data set 정리 및 기록할 방법 구상

추가적인 사항은 내일 작성할 예정

**Comment by taeyang1224** [comment]
211001 - To do
- [x]  카테고리 테이블 생성
- [x]  다희님과 변수명 맞추기
- [x] click_data 전처리
- [x] 코드정리
- [x] 인터넷 시각화 다희님께 전달

**Comment by taeyang1224** [comment]
211001 - 내용 정리

 - 변수 및 카테고리 테이블 정리 완료 (다희님과 변수명 모두 통일 이후, 변수명 통일) -> 구글 드라이브 DOC 폴더 업로드 완료
 - DataBase set (COVID, Transaction) 전처리 및 표준화 완료
 - DataBase set 업로드 완료 (COVID, Naver_Trend, Transaction)-> 구글 드라이브 DB 폴더 업로드 완료
 - Click_data 전처리 완료(디지털/가전, 문화공연, 사무용품, 식품, 여행, 출산/육아 항목 PC_Data) -> 구글 드라이브 DB 폴더 업로드 완료 -> 전처리 issue 발생으로 처리 후 다시 DB 폴더에 업로드 할 예정
 - click_data 전처리 하는 과정 중 모든 항목 전처리를 완료 -> 하지만 문화공연 part 조회수 결측치 발생 -> age10, age60 data에서 row의 숫자가 다름을 파악 -> age10 = 7개의 row 부족, age60 = 9개의 row 부족을 확인 
 - 전처리 진행중 사용했던 Code 기본 틀 정리 완료 -> Click Data 전처리 하면서 부가적인 내용 생성으로 코드 doc 다듬어야함
 - Internet 시각화 및 covid 확진자 시각화 다희님에게 모두 전달 -> 다희님께서 시각화 정리 doc 생성

**Comment by taeyang1224** [comment]
211002 - To do
- [x] 전처리 code 다듬고 정리하기
- [x] click_data_pc 결측치 처리 마무리짓기
- [x] click_data_mobile 전처리 -> 일별 data를 월별 data로 변경 *출산/육아, 디지털/가전 mobile data 아직 없음 -> data set은 있지만 필요한 항목은 아니기 때문에 처리 하지 않아도 됨

진행하면서 to do list는 추가할 예정
- [x] 변수 테이블 수정

**Comment by taeyang1224** [comment]
211003 - To do 

- [ ] 변수 테이블 최종 정리
- [x] click_data_mobile 전처리
- [ ] 그래프로 나온 결과등 수치를 문서화

**Comment by taeyang1224** [comment]
211003 - issue

- click_data pc 문화/공연 항목 결측치 처리
age10-19 : 8 rows null 값 ->평균값 23.51675 으로 대체
age60- : 11 rows null 값 ->평균값 : 13.99536 으로 대체

- click_data mobile 전처리 완료 -> 특이사항 없음 -> 구글드라이브 DB 폴더 업로드 완료
- click_data_pc 와 click_data_mo .describe() 비교 해봄 -> 전반적으로 큰 차이는 없음

211004 - To do
- 전처리 코드 정리 완료 -> DB 폴더에 업로드 완료
- 변수테이블 정리 아직 미흡 -> 10.04 최종 완료 예정
- 그래프로 나온 결과등 수치를 문서화 -> 다희님이 가진 그래프를 보고 전체적으로 정리하는것이 낫다고 생각
- 다희님 시각화 정리 완료 하면 최종 PT에 사용할 그래프와 전반적인 흐름 정리해보기

**Comment by taeyang1224** [comment]
211004 - To do 

1. 코드 정리 및 전처리 notion 테이블 구상 및 업로드
- 코드 주석 달고 정리하기
- data set의 대한 shape이나 기본적인 설명 구글드라이브 내용을 notion으로 정리
- notion part.4 데이터 전처리 테이블 흐름 구상
2. 주요 내용 문서화 정리
- ex) 주요 내용 or 항목, 확진자 수 기준 산업군별 수치가 높은 상위 5개 산업군, 하위 5개 산업군 -> 3개정도 등 및 문서화
-  가설에 대한 각 항목별 중요 내용 -> 문서화 작업 (금액, 비율)
3. 다희님과 notion part 6 모델평가 같이 정리, 가설에 따른 포지셔닝 및 인사이트 정리
4.  전체적인 issue 정리 및 notion 전체적인 추가사항 업로드

**Comment by taeyang1224** [comment]
- 추가적인 To do
- [x] 2. 데이터 수집 part 정리
- [x] 3. 데이터 탐색 part 정리
- [x] 4. 데이터 전처리 part 정리
- [x] Codebase - Processing Data 정리

코드정리 내일 마무리 하기
